import re

with open('/home/z/my-project/arcano-deploy/js/pages.js', 'r') as f:
    lines = f.readlines()

# Find start line ("VENTA POR QR")
start_line = -1
end_line = -1
for i, line in enumerate(lines):
    if 'VENTA POR QR' in line:
        start_line = i
        break
for i, line in enumerate(lines):
    if 'STOCK' in line and i > start_line and '====' in line:
        end_line = i
        break

print(f'Found QR block: lines {start_line+1} to {end_line+1}')

new_block = []
new_block.append('  /* ================================================================')
new_block.append('     VENTA POR CAMARA (OCR - lectura de etiquetas)')
new_block.append('     ================================================================ */')
new_block.append('  _camStream: null,')
new_block.append('  _camCart: [],')
new_block.append('  _camOcrRunning: false,')
new_block.append('')
new_block.append("  /** Open camera modal for label-reading sale */")
new_block.append("  formVentaQR() {")
new_block.append('    Pages._camCart = [];')
new_block.append('    var modal = document.createElement(\'div\');')
new_block.append("    modal.className = 'modal-overlay';")
new_block.append("    modal.id = 'cam-venta-modal';")
new_block.append('    modal.innerHTML =')
new_block.append("      '<div class=\"modal modal-lg\" style=\"max-width:520px\">' +")
new_block.append("        '<div class=\"modal-header\"><h3>\\u{1F4F7} Venta por Camara</h3>' +")
new_block.append("          '<button class=\"btn btn-ghost\" onclick=\"Pages.closeVentaCam()\">X</button></div>' +")
new_block.append("        '<div class=\"modal-body\" style=\"padding:0\">' +")
new_block.append("          '<div style=\"position:relative;background:#000\">' +")
new_block.append("            '<video id=\"cam-video\" autoplay playsinline style=\"width:100%;display:block;max-height:320px;object-fit:cover\"></video>' +")
new_block.append("            '<canvas id=\"cam-canvas\" style=\"display:none\"></canvas>' +")
new_block.append("            '<div id=\"cam-scan-line\" style=\"position:absolute;top:50%;left:10%;right:10%;height:2px;background:var(--gold);opacity:0.6;transform:translateY(-50%);animation:scanLine 2s ease-in-out infinite;pointer-events:none\"></div>' +")
new_block.append("            '<style>@keyframes scanLine{0%,100%{top:calc(50% - 50px)}50%{top:calc(50% + 50px)}}</style>' +")
new_block.append("          '</div>' +")
new_block.append("          '<div id=\"cam-status\" style=\"padding:12px 16px;background:var(--bg-card);color:var(--muted);font-size:0.85rem;text-align:center\">' +")
new_block.append("            'Apunta la camara a la etiqueta del producto' +")
new_block.append("          '</div>' +")
new_block.append("          '<div style=\"display:flex;justify-content:center;gap:8px;padding:8px 16px;background:var(--bg-card)\">' +")
new_block.append("            '<button class=\"btn btn-sm btn-outline\" id=\"cam-flash-btn\" onclick=\"Pages.toggleCamFlash()\">\\u{1F526} Flash</button>' +")
new_block.append("            '<button class=\"btn btn-sm btn-gold\" onclick=\"Pages.captureAndRead()\">\\u{1F4F7} Capturar</button>' +")
new_block.append("          '</div>' +")
new_block.append("          '<!-- Confirmation area -->' +")
new_block.append("          '<div id=\"cam-confirm-area\" style=\"padding:12px 16px;display:none\">' +")
new_block.append("            '<div style=\"font-size:0.75rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px\">Producto detectado</div>' +")
new_block.append("            '<div id=\"cam-detected-text\" style=\"font-size:0.8rem;color:var(--muted);margin-bottom:8px;font-style:italic\"></div>' +")
new_block.append("            '<div style=\"display:flex;align-items:center;gap:8px;flex-wrap:wrap\">' +")
new_block.append("              '<select class=\"input\" id=\"cam-prod-select\" style=\"flex:1;min-width:140px\"><option value=\"\">Seleccionar producto</option></select>' +")
new_block.append("              '<select class=\"input\" id=\"cam-talla-select\" style=\"width:120px\"><option value=\"chico\">Chico</option><option value=\"grande\">Grande</option></select>' +")
new_block.append("              '<button class=\"btn btn-sm btn-gold\" onclick=\"Pages.addCamProduct()\">+ Agregar</button>' +")
new_block.append("              '<button class=\"btn btn-sm btn-outline\" onclick=\"Pages.cancelCamDetect()\">Seguir leyendo</button>' +")
new_block.append("            '</div>' +")
new_block.append("          '</div>' +")
new_block.append("          '<!-- Cart -->' +")
new_block.append("          '<div id=\"cam-cart-area\" style=\"padding:12px 16px;max-height:200px;overflow-y:auto;display:none\">' +")
new_block.append("            '<div style=\"font-size:0.75rem;color:var(--muted);text-transform:uppercase;letter-spacing:0.05em;margin-bottom:8px\">Productos agregados</div>' +")
new_block.append("            '<div id=\"cam-cart-items\"></div>' +")
new_block.append("          '</div>' +")
new_block.append("          '<!-- Total and confirm -->' +")
new_block.append("          '<div id=\"cam-total-area\" style=\"padding:12px 16px;border-top:1px solid var(--border);display:none\">' +")
new_block.append("            '<div class=\"venta-total-box\">Total: $<span id=\"cam-venta-total\">0</span></div>' +")
new_block.append("            '<button class=\"btn btn-gold btn-block mt-8\" onclick=\"Pages.confirmarVentaCam()\">\\u{2705} Confirmar Venta</button>' +")
new_block.append("          '</div>' +")
new_block.append("        '</div>' +")
new_block.append("      '</div>';")
new_block.append("    document.body.appendChild(modal);")
new_block.append("    setTimeout(function() { Pages.startCamera(); }, 300);")
new_block.append('  },')
new_block.append('')
new_block.append('  startCamera() {')
new_block.append("    var video = document.getElementById('cam-video');")
new_block.append('    if (!video) return;')
new_block.append("    var statusEl = document.getElementById('cam-status');")
new_block.append("    navigator.mediaDevices.getUserMedia({")
new_block.append("      video: { facingMode: 'environment', width: { ideal: 1280 }, height: { ideal: 720 } }")
new_block.append('    }).then(function(stream) {')
new_block.append('      Pages._camStream = stream;')
new_block.append('      video.srcObject = stream;')
new_block.append('      video.play();')
new_block.append("      if (statusEl) statusEl.textContent = 'Apunta la camara a la etiqueta del producto';")
new_block.append("    }).catch(function(err) {")
new_block.append("      if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--red)\">No se pudo acceder a la camara: ' + err.message + '</span>';")
new_block.append('    });')
new_block.append('  },')
new_block.append('')
new_block.append('  stopCamera() {')
new_block.append('    if (Pages._camStream) {')
new_block.append('      Pages._camStream.getTracks().forEach(function(t) { t.stop(); });')
new_block.append('      Pages._camStream = null;')
new_block.append('    }')
new_block.append('    Pages._camOcrRunning = false;')
new_block.append('  },')
new_block.append('')
new_block.append('  toggleCamFlash() {')
new_block.append('    if (!Pages._camStream) return;')
new_block.append('    var track = Pages._camStream.getVideoTracks()[0];')
new_block.append('    if (!track) return;')
new_block.append('    var caps = track.getCapabilities ? track.getCapabilities() : {};')
new_block.append('    if (caps.torch) {')
new_block.append('      var isOn = (track.getSettings && track.getSettings().torch) || false;')
new_block.append("      track.applyConstraints({ advanced: [{ torch: !isOn }] });")
new_block.append("      var btn = document.getElementById('cam-flash-btn');")
new_block.append("      if (btn) btn.textContent = isOn ? '\\u{1F526} Flash' : '\\u{1F526} Flash ON';")
new_block.append('    }')
new_block.append('  },')
new_block.append('')
new_block.append('  captureAndRead() {')
new_block.append('    if (Pages._camOcrRunning) return;')
new_block.append("    var video = document.getElementById('cam-video');")
new_block.append("    var canvas = document.getElementById('cam-canvas');")
new_block.append("    var statusEl = document.getElementById('cam-status');")
new_block.append('    if (!video || !canvas || video.readyState < 2) return;')
new_block.append('    if (navigator.vibrate) navigator.vibrate(50);')
new_block.append('    canvas.width = video.videoWidth;')
new_block.append('    canvas.height = video.videoHeight;')
new_block.append('    var ctx = canvas.getContext(\'2d\');')
new_block.append('    ctx.drawImage(video, 0, 0);')
new_block.append("    var imageData = canvas.toDataURL('image/png');")
new_block.append('    Pages._camOcrRunning = true;')
new_block.append("    if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--gold)\">Leyendo etiqueta...</span>';")
new_block.append('    if (typeof Tesseract === \'undefined\') {')
new_block.append("      if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--red)\">Libreria OCR no disponible. Verifica conexion a internet.</span>';")
new_block.append('      Pages._camOcrRunning = false;')
new_block.append('      return;')
new_block.append('    }')
new_block.append("    Tesseract.recognize(imageData, 'spa+eng', {")
new_block.append('      logger: function() {}')
new_block.append('    }).then(function(result) {')
new_block.append('      Pages._camOcrRunning = false;')
new_block.append('      var text = (result && result.data && result.data.text) || \'\';')
new_block.append('      text = text.replace(/\\n/g, \' \').replace(/\\s+/g, \' \').trim();')
new_block.append('      Pages.handleOCRResult(text);')
new_block.append('    }).catch(function(err) {')
new_block.append('      Pages._camOcrRunning = false;')
new_block.append("      if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--red)\">Error al leer: ' + err.message + '</span>';")
new_block.append('    });')
new_block.append('  },')
new_block.append('')
new_block.append('  handleOCRResult(text) {')
new_block.append("    var statusEl = document.getElementById('cam-status');")
new_block.append("    var confirmArea = document.getElementById('cam-confirm-area');")
new_block.append("    var detectedTextEl = document.getElementById('cam-detected-text');")
new_block.append("    var prodSelect = document.getElementById('cam-prod-select');")
new_block.append('    if (!text || text.length < 2) {')
new_block.append("      if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--red)\">No se detecto texto. Intenta de nuevo.</span>';")
new_block.append("      setTimeout(function() { if (statusEl) statusEl.textContent = 'Apunta la camara a la etiqueta del producto'; }, 2000);")
new_block.append('      return;')
new_block.append('    }')
new_block.append('    var especias = ArcanoDB.getEspecias();')
new_block.append('    var blends = ArcanoDB.getBlends();')
new_block.append('    var allProducts = [];')
new_block.append('    for (var i = 0; i < especias.length; i++) { allProducts.push({ tipo: \'especia\', producto: especias[i] }); }')
new_block.append('    for (var i = 0; i < blends.length; i++) { allProducts.push({ tipo: \'blend\', producto: blends[i] }); }')
new_block.append("    var ocrLower = text.toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g, '');")
new_block.append('    var scored = [];')
new_block.append('    for (var i = 0; i < allProducts.length; i++) {')
new_block.append('      var p = allProducts[i];')
new_block.append("      var name = (p.producto.nombre || '').toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g, '');")
new_block.append("      var nameWords = name.split(/\\s+/);")
new_block.append('      var matchCount = 0;')
new_block.append('      for (var w = 0; w < nameWords.length; w++) {')
new_block.append('        if (nameWords[w].length < 2) continue;')
new_block.append('        if (ocrLower.indexOf(nameWords[w]) !== -1) matchCount++;')
new_block.append('      }')
new_block.append('      var score = nameWords.length > 0 ? matchCount / nameWords.length : 0;')
new_block.append('      if (ocrLower.indexOf(name) !== -1) score = Math.max(score, 1.0);')
new_block.append('      if (name.length >= 3 && ocrLower.indexOf(name.substring(0, Math.min(name.length, 6))) !== -1) score = Math.max(score, 0.7);')
new_block.append('      if (score >= 0.5) scored.push({ tipo: p.tipo, producto: p.producto, score: score });')
new_block.append('    }')
new_block.append("    scored.sort(function(a, b) { return b.score - a.score; });")
new_block.append('    if (confirmArea) confirmArea.style.display = \'block\';')
new_block.append("    if (detectedTextEl) detectedTextEl.textContent = 'Texto leido: \"' + text.substring(0, 80) + (text.length > 80 ? '...' : '') + '\"';")
new_block.append('    if (prodSelect) {')
new_block.append("      prodSelect.innerHTML = '<option value=\"\">Seleccionar producto</option>';")
new_block.append('      if (scored.length > 0) {')
new_block.append('        for (var i = 0; i < Math.min(scored.length, 5); i++) {')
new_block.append('          var s = scored[i];')
new_block.append('          var pct = Math.round(s.score * 100);')
new_block.append("          prodSelect.innerHTML += '<option value=\"' + s.tipo + '|' + s.producto.id + '\">' + s.producto.nombre + ' (' + pct + '%)</option>';")
new_block.append('        }')
new_block.append('        if (scored[0].score >= 0.7) {')
new_block.append("          prodSelect.value = scored[0].tipo + '|' + scored[0].producto.id;")
new_block.append('        }')
new_block.append("        if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--green)\">Producto detectado - confirma abajo</span>';")
new_block.append('      } else {')
new_block.append("        if (statusEl) statusEl.innerHTML = '<span style=\"color:var(--red)\">No se encontro producto. Selecciona manualmente.</span>';")
new_block.append('        for (var i = 0; i < allProducts.length; i++) {')
new_block.append('          var ap = allProducts[i];')
new_block.append("          prodSelect.innerHTML += '<option value=\"' + ap.tipo + '|' + ap.producto.id + '\">' + ap.producto.nombre + '</option>';")
new_block.append('        }')
new_block.append('      }')
new_block.append('    }')
new_block.append('  },')
new_block.append('')
new_block.append('  cancelCamDetect() {')
new_block.append("    var confirmArea = document.getElementById('cam-confirm-area');")
new_block.append("    if (confirmArea) confirmArea.style.display = 'none';")
new_block.append("    var statusEl = document.getElementById('cam-status');")
new_block.append("    if (statusEl) statusEl.textContent = 'Apunta la camara a la etiqueta del producto';")
new_block.append('  },')
new_block.append('')
new_block.append('  addCamProduct() {')
new_block.append("    var prodVal = document.getElementById('cam-prod-select').value;")
new_block.append("    var tallaVal = document.getElementById('cam-talla-select').value;")
new_block.append("    if (!prodVal) { alert('Selecciona un producto'); return; }")
new_block.append("    var parts = prodVal.split('|');")
new_block.append('    var tipo = parts[0];')
new_block.append('    var prodId = Number(parts[1]);')
new_block.append("    var producto = tipo === 'blend' ? ArcanoDB.getBlend(prodId) : ArcanoDB.getEspecia(prodId);")
new_block.append("    if (!producto) { alert('Producto no encontrado'); return; }")
new_block.append("    var stockKey = tallaVal === 'grande' ? 'stockGrande' : 'stockChico';")
new_block.append("    var precioKey = tallaVal === 'grande' ? 'precioGrande' : 'precioChico';")
new_block.append('    var stock = producto[stockKey] || 0;')
new_block.append('    var precio = producto[precioKey] || 0;')
new_block.append("    if (stock <= 0) { alert('Sin stock de ' + producto.nombre + ' (' + tallaVal + ')'); return; }")
new_block.append('    var found = false;')
new_block.append('    for (var i = 0; i < Pages._camCart.length; i++) {')
new_block.append('      if (Pages._camCart[i].tipo === tipo && Pages._camCart[i].productoId === prodId && Pages._camCart[i].talla === tallaVal) {')
new_block.append('        if (Pages._camCart[i].cantidad < stock) Pages._camCart[i].cantidad++;')
new_block.append('        found = true;')
new_block.append('        break;')
new_block.append('      }')
new_block.append('    }')
new_block.append('    if (!found) {')
new_block.append("      Pages._camCart.push({ tipo: tipo, productoId: prodId, talla: tallaVal, cantidad: 1, precioUnitario: precio });")
new_block.append('    }')
new_block.append('    if (navigator.vibrate) navigator.vibrate([50, 50, 50]);')
new_block.append('    Pages.renderCamCart();')
new_block.append('    Pages.cancelCamDetect();')
new_block.append('  },')
new_block.append('')
new_block.append('  renderCamCart() {')
new_block.append("    var cartArea = document.getElementById('cam-cart-area');")
new_block.append("    var cartItems = document.getElementById('cam-cart-items');")
new_block.append("    var totalArea = document.getElementById('cam-total-area');")
new_block.append("    var totalSpan = document.getElementById('cam-venta-total');")
new_block.append('    if (Pages._camCart.length === 0) {')
new_block.append("      if (cartArea) cartArea.style.display = 'none';")
new_block.append("      if (totalArea) totalArea.style.display = 'none';")
new_block.append('      return;')
new_block.append('    }')
new_block.append("    if (cartArea) cartArea.style.display = 'block';")
new_block.append("    if (totalArea) totalArea.style.display = 'block';")
new_block.append("    var h = '';")
new_block.append('    var total = 0;')
new_block.append('    for (var i = 0; i < Pages._camCart.length; i++) {')
new_block.append('      var item = Pages._camCart[i];')
new_block.append("      var prod = item.tipo === 'blend' ? ArcanoDB.getBlend(item.productoId) : ArcanoDB.getEspecia(item.productoId);")
new_block.append("      var nombre = prod ? prod.nombre : '?';")
new_block.append('      var sub = item.cantidad * item.precioUnitario;')
new_block.append('      total += sub;')
new_block.append("      h += '<div style=\"display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--border)\">' +")
new_block.append("        '<div><div style=\"font-weight:600;font-size:0.9rem\">' + nombre + '</div>' +")
new_block.append("        '<div style=\"font-size:0.75rem;color:var(--muted)\">' + item.talla + ' | $' + item.precioUnitario.toLocaleString() + ' c/u</div></div>' +")
new_block.append("        '<div style=\"display:flex;align-items:center;gap:8px\">' +")
new_block.append("        '<button class=\"btn btn-sm btn-outline\" onclick=\"Pages.camCartQty(' + i + ',-1)\">-</button>' +")
new_block.append("        '<span style=\"font-weight:700;min-width:24px;text-align:center\">' + item.cantidad + '</span>' +")
new_block.append("        '<button class=\"btn btn-sm btn-outline\" onclick=\"Pages.camCartQty(' + i + ',1)\">+</button>' +")
new_block.append("        '<span style=\"font-weight:700;color:var(--gold);min-width:70px;text-align:right\">$' + sub.toLocaleString() + '</span>' +")
new_block.append("        '<button class=\"btn btn-sm btn-red\" onclick=\"Pages.camCartRemove(' + i + ')\">X</button>' +")
new_block.append("        '</div></div>';")
new_block.append('    }')
new_block.append('    if (cartItems) cartItems.innerHTML = h;')
new_block.append('    if (totalSpan) totalSpan.textContent = total.toLocaleString();')
new_block.append('  },')
new_block.append('')
new_block.append('  camCartQty(idx, delta) {')
new_block.append('    if (!Pages._camCart[idx]) return;')
new_block.append('    var item = Pages._camCart[idx];')
new_block.append('    var newCant = item.cantidad + delta;')
new_block.append("    var producto = item.tipo === 'blend' ? ArcanoDB.getBlend(item.productoId) : ArcanoDB.getEspecia(item.productoId);")
new_block.append("    var stockKey = item.talla === 'grande' ? 'stockGrande' : 'stockChico';")
new_block.append('    var maxStock = producto ? (producto[stockKey] || 0) : 0;')
new_block.append('    if (newCant < 1 || newCant > maxStock) return;')
new_block.append('    item.cantidad = newCant;')
new_block.append('    Pages.renderCamCart();')
new_block.append('  },')
new_block.append('')
new_block.append('  camCartRemove(idx) {')
new_block.append('    Pages._camCart.splice(idx, 1);')
new_block.append('    Pages.renderCamCart();')
new_block.append('  },')
new_block.append('')
new_block.append('  confirmarVentaCam() {')
new_block.append("    if (Pages._camCart.length === 0) { alert('No hay productos en la venta'); return; }")
new_block.append("    if (!confirm('Registrar venta de ' + Pages._camCart.length + ' producto(s)?')) return;")
new_block.append('    try {')
new_block.append('      ArcanoDB.saveVenta({')
new_block.append("        fecha: new Date().toISOString().slice(0, 10),")
new_block.append('        items: JSON.parse(JSON.stringify(Pages._camCart))')
new_block.append('      });')
new_block.append('      Pages.closeVentaCam();')
new_block.append("      App.renderPage('ventas');")
new_block.append('    } catch (err) {')
new_block.append("      alert('Error: ' + err.message);")
new_block.append('    }')
new_block.append('  },')
new_block.append('')
new_block.append('  closeVentaCam() {')
new_block.append('    Pages.stopCamera();')
new_block.append("    var modal = document.getElementById('cam-venta-modal');")
new_block.append('    if (modal) modal.remove();')
new_block.append('    Pages._camCart = [];')
new_block.append('  },')
new_block.append('')

# Replace lines
result = lines[:start_line] + [l + '\n' for l in new_block] + lines[end_line:]

with open('/home/z/my-project/arcano-deploy/js/pages.js', 'w') as f:
    f.writelines(result)

print(f'Done: replaced QR block (lines {start_line+1}-{end_line}) with OCR camera block ({len(new_block)} lines)')
